LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES:= vidservice.c 

LOCAL_MODULE:= vidservice

LOCAL_C_INCLUDES := $(KERNEL_HEADERS)

LOCAL_CFLAGS := 

LOCAL_SHARED_LIBRARIES := libcutils
LOCAL_MODULE_TAGS := eng
include $(BUILD_EXECUTABLE)
